---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-service
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: java-service
  endpoints:
    - path: /backend/manage/prometheus
      port: java-service
