services:
  jaeger:
    image: "jaegertracing/jaeger:2.2.0"
    container_name: jaeger
    command: ["--config", "/etc/jaeger/config.yml"]
    ports:
      - "16686:16686"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:16686" ]
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - "./docker/jaeger/config.yml:/etc/jaeger/config.yml"
