spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID:7uHBa1xYenYPjX7UhOonuGhOWvxLUwYM}
            client-secret: ${AUTH0_CLIENT_SECRET:TbNIL8SJx38sDDweRqWsRaqWKU7Q6UrWr0f6DzKwlLh48892GE4KfoKR1cfIe87e}
            redirect-uri: ${AUTH0_REDIRECT_URI:{baseUrl}/login/oauth2/code/auth0}
            scope:
              - openid
              - email
              - profile
        provider:
          auth0:
            issuer-uri: ${AUTH0_ISSUER_URI:https://romanowalex.eu.auth0.com/}
