spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:application}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:sJk0f1ZjftWyyrwHFGIIfarqt1DFDedC}
            redirect-uri: ${KEYCLOAK_REDIRECT_URI:{baseUrl}/login/oauth2/code/keycloak}
            scope:
              - openid
              - email
              - profile
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8100/realms/todo-list}
            user-name-attribute: preferred_username
