global:
  scrape_interval: 5s

scrape_configs:
  - job_name: backend
    metrics_path: '/backend/manage/prometheus'
    static_configs:
      - targets: [ backend-todo-list:8080 ]

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: [ cadvisor:8080 ]

  - job_name: node-exporter
    static_configs:
      - targets: [ "node-exporter:9100" ]

  - job_name: trace-metrics
    static_configs:
      - targets: [ "jaeger:8889" ]
